# Generated by Django 3.2.7 on 2021-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='colour',
            field=models.CharField(default='#FF0000', max_length=100),
        ),
    ]
