# Generated by Django 3.2.7 on 2021-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_pins_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='slug',
        ),
        migrations.AddField(
            model_name='pins',
            name='lat',
            field=models.DecimalField(decimal_places=15, default=51.511511, max_digits=20),
        ),
        migrations.AddField(
            model_name='pins',
            name='lng',
            field=models.DecimalField(decimal_places=15, default=-0.133492, max_digits=20),
        ),
    ]
