# Generated by Django 3.2.7 on 2021-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_auto_20210907_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=51.511511, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pins',
            name='lng',
            field=models.DecimalField(decimal_places=10, default=-0.133492, max_digits=20),
        ),
    ]
