# Generated by Django 3.2.7 on 2021-09-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_auto_20210907_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='pin',
        ),
    ]
