# Generated by Django 3.2.7 on 2021-09-07 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0005_remove_pins_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumb', models.CharField(blank=True, max_length=100)),
                ('colour', models.CharField(default='#FF0000', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pin_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pins.pins')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lists',
            },
        ),
    ]
