# Generated by Django 3.2.7 on 2021-09-08 13:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='pin_id',
        ),
        migrations.AddField(
            model_name='lists',
            name='list_pins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
